# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: zsh

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: 113

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: auto

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: floating
  title: deew
  style:
    border: 0px black solid
    # boxShadow: none
    margin: 0px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "FiraCode Nerd Font Mono"

# The size of the font
fontSize: 12

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "transparent"
  foreground: "#afafaf"
  cursor: "rgb(224,224,224)"
  black: "rgb(32,32,32)"
  red: "rgb(239,41,41)"
  green: "rgb(175,255,0)"
  yellow: "rgb(255,135,0)"
  blue: "rgb(31,91,255)"
  magenta: "rgb(209,138,255)"
  cyan: "rgb(135,255,255)"
  white: "rgb(198,198,198)"
  brightBlack: "rgb(178,178,178)"
  brightRed: "rgb(255,75,75)"
  brightGreen: "rgb(161,219,0)"
  brightYellow: "rgb(252,233,79)"
  brightBlue: "rgb(95,175,215)"
  brightMagenta: "rgb(255,78,163)"
  brightCyan: "rgb(0,215,175)"
  brightWhite: "rgb(253,253,231)"
